Implemented Select/Deselect group. FIX #39
HaikuArchives/GenesisCommander pull request #40
Opened 2020-02-09 19:06 UTC by ocerman

This PR implements Select/Deselect group. User can define group by fnmatch filename pattern, like "*.zip"

2020-02-10 08:11 UTC, humdingerb requested changes
Works nicely!
There are quite a few stray whitespaces in there. Koder can show them very well (activate in its settings).

2020-02-10 08:11 UTC, humdingerb commented on src/GenesisSelectGroupWindow.h
> +#include <Window.h>
Alpha-sort headers

2020-02-10 21:19 UTC, ocerman commented
@humdingerb Didn't know that Koder have this feature, thanks.

I have removed trailing whitespaces in newly created files, I will try to clean all other project files later.

2020-02-11 18:13 UTC, merged

2020-02-11 18:14 UTC, humdingerb commented
Thanks!