Added option to change Editor app
HaikuArchives/GenesisCommander pull request #58
Opened 2020-03-29 17:52 UTC by ocerman

This PR adds option to change F4 Editor in the preferences screen.

2020-03-30 07:03 UTC, humdingerb reviewed
It may be neat to just have the pop-up menu to select the editor app. The text field isn't really needed.
In that case it should be put at the top, before "Terminal window title". Looks better...

2020-03-30 07:03 UTC, humdingerb commented on src/GenesisPanelView.cpp
> +				BAlert *alert = new BAlert("Genesis","You have to choose editor app in the Preferences screen","Okay","Open Preferences",NULL,B_WIDTH_AS_USUAL,B_OFFSET_SPACING,B_STOP_ALERT);
Suggestion, considering standard Haiku naming: Choose->Select (see FileTypes prefs e.g.), Okay->OK
```suggestion
				BAlert *alert = new BAlert("Genesis","You have to select an editor application in the Genesis preferences","OK","Open preferences",NULL,B_WIDTH_AS_USUAL,B_OFFSET_SPACING,B_STOP_ALERT);
```

2020-03-30 07:03 UTC, humdingerb commented on src/GenesisPanelView.cpp
> +				BAlert *alert = new BAlert("Genesis","Error while opening Editor application.\nYou can change editor app in the Preferences screen.","Okay","Open Preferences",NULL,B_WIDTH_AS_USUAL,B_OFFSET_SPACI
```suggestion
				BAlert *alert = new BAlert("Genesis","Error while opening the editor application.\nYou can change the editor app in the Gensis preferences.","OK","Open preferences",NULL,B_WIDTH_AS_USUAL,B_OFFSET_SPACING,B_STOP_ALERT);
```

2020-03-30 07:03 UTC, humdingerb commented on src/GenesisPreferencesWindow.cpp
> +	m_EditorsMenu = new BMenu("choose ...",B_ITEMS_IN_COLUMN);
```suggestion
	m_EditorsMenu = new BMenu("Select ...",B_ITEMS_IN_COLUMN);
```

You can also replace "..." with B_UTF8_ELLIPSIS everywhere.

2020-03-30 07:03 UTC, humdingerb commented on src/GenesisPreferencesWindow.cpp
> +	m_EditorApp = new BTextControl("editor", "F4 Editor application", "", NULL, B_WILL_DRAW|B_NAVIGABLE);
```suggestion
	m_EditorApp = new BTextControl("editor", "Editor application (F4)", "", NULL, B_WILL_DRAW|B_NAVIGABLE);
```

That way the "F4" isn't that prominent; the user may have set the option not to show function keys.

2020-04-02 18:34 UTC, ocerman commented
Hello @humdingerb ,

Yes, propably the text field is not really needed. It would be usefull when Genesis would failed to detect some apps - but that seems to be working without any problems so far.

I will try to change it to pop-up menu in the future.

I have also accepted your other suggestions.

2020-04-03 05:53 UTC, humdingerb requested changes

2020-04-03 05:53 UTC, humdingerb commented on src/GenesisPanelView.cpp
> +				BAlert *alert = new BAlert("Genesis","Error while opening the editor application.\nYou can change the editor app in the Gensis preferences.","OK","Open preferences",NULL,B_WIDTH_AS_USUAL,B_OFFSET
Little typo :)
```suggestion
				BAlert *alert = new BAlert("Genesis","Error while opening the editor application.\nYou can change the editor app in the Genesis preferences.","OK","Open preferences",NULL,B_WIDTH_AS_USUAL,B_OFFSET_SPACING,B_STOP_ALERT);
```

2020-04-03 05:58 UTC, humdingerb commented
> Yes, propably the text field is not really needed. It would be usefull when Genesis would failed to detect some apps - but that seems to be working without any problems so far.

If needed, there could be an additional menu item "Other..." that opens a file dialog to pick an app manually, that is then added to the menu. When Genesis launches, it will then have to check if the app is still there and remove that menu item if it isn't.
But I suppose, it'll work well enough as it is, as long as the editor is correctly reporting its supported types etc.

2020-04-03 17:25 UTC, merged

2020-04-03 17:25 UTC, humdingerb commented
Thanks!